### ISSUE TITLE
Track gobject-introspection bug for MSYS2/MinGW

### ISSUE THREAD

**Issue by zmughal** [project-renard/p5-Alien-Graphene#2]
<https://github.com/ebassi/graphene/issues/112>, <https://bugzilla.gnome.org/show_bug.cgi?id=791902>.

**Comment by lazka** [comment]
should work now, see https://github.com/Alexpux/MINGW-packages/pull/3373

**Comment by zmughal** [comment]
Brilliant! Thanks!
